# -*- coding: utf-8 -*-
"""sarsa_windy_gridworld_01.ipynb

Automatically generated by Colab.


"""

# =====================================================================
# SARSA
#
# =====================================================================
# _Aprendizaje por Refuerzo I
# _Maestria en Inteligencia Artificial
# _UBA
# _2025
# =====================================================================

'''

Windy Gridworld
===============



'''

import numpy as np
import matplotlib.pyplot as plt
from collections import defaultdict
import random

plt.rcParams.update({
    'figure.facecolor': '#2b2b2b',     # fondo exterior
    'axes.facecolor':   '#2b2b2b',     # fondo del área del gráfico
    'axes.edgecolor':   '#cccccc',     # borde de los ejes
    'axes.labelcolor':  '#cccccc',     # etiquetas de los ejes
    'xtick.color':      '#cccccc',     # color de los números en el eje X
    'ytick.color':      '#cccccc',     # color de los números en el eje Y
    'text.color':       '#cccccc',     # color del título y textos
    'grid.color':       '#444444',     # color de la grilla
})

# --- Parámetros del Entorno (Globales) ---
GRID_HEIGHT = 7
GRID_WIDTH = 10
# Las fuerzas del viento para cada columna (0 significa sin viento)
WIND = np.array([0, 0, 0, 1, 1, 1, 2, 2, 1, 0])
START_STATE = (3, 0)
GOAL_STATE = (3, 7)
# Acciones: 0: Arriba, 1: Abajo, 2: Izquierda, 3: Derecha
ACTIONS = [(-1, 0), (1, 0), (0, -1), (0, 1)]
NUM_ACTIONS = len(ACTIONS)
REWARD_STEP = -1 # Recompensa por cada paso

# --- Parámetros del Agente (Globales o Configurables) ---
ALPHA = 0.5 # Tasa de aprendizaje
GAMMA = 1.0 # Factor de descuento (1.0 para tareas no descontadas)
EPSILON = 0.1 # Probabilidad de exploración (política epsilon-greedy)

# --- Estado del Agente (Tabla Q Global) ---
# Usa defaultdict para manejar estados/acciones no vistos fácilmente
# La clave es el estado (tupla), el valor es un array numpy de valores Q para cada acción
q_table = defaultdict(lambda: np.zeros(NUM_ACTIONS))

# --- Funciones del Entorno ---

def env_step(state, action_index):
    """
    Realiza un paso en el entorno Windy Gridworld.
    Args:
        state (tuple): Estado actual (fila, columna).
        action_index (int): Índice de la acción a tomar.
    Returns:
        tuple: (next_state, reward, done)
               next_state (tuple): El estado después de tomar la acción y aplicar el viento.
               reward (int): La recompensa recibida.
               done (bool): True si el next_state es el estado objetivo.
    """
    if state == GOAL_STATE:
        return state, 0, True # Ya en el objetivo, no hay movimiento ni recompensa

    r, c = state
    dr, dc = ACTIONS[action_index]

    # Calcula la posición tentativa después de la acción
    next_r, next_c = r + dr, c + dc

    # Aplica el efecto del viento basado en la columna actual
    current_col_for_wind = c
    # Verifica si el movimiento horizontal fue válido para usar la columna correcta
    if 0 <= next_c < GRID_WIDTH:
         current_col_for_wind = next_c

    wind_effect = WIND[current_col_for_wind]
    next_r -= wind_effect # El viento empuja hacia arriba (disminuye índice de fila)

    # Verifica los límites de la cuadrícula después de acción + viento
    next_r = np.clip(next_r, 0, GRID_HEIGHT - 1)
    next_c = np.clip(next_c, 0, GRID_WIDTH - 1)

    next_state = (int(next_r), int(next_c))

    # Determina la recompensa y si se ha terminado
    if next_state == GOAL_STATE:
        reward = 0 # Recompensa final al llegar
        done = True
    else:
        reward = REWARD_STEP
        done = False

    return next_state, reward, done

# --- Funciones del Agente ---

def choose_action(state, current_q_table, current_epsilon):
    """
    Elige una acción usando una política epsilon-greedy.
    Args:
        state (tuple): El estado actual.
        current_q_table (defaultdict): La tabla Q actual.
        current_epsilon (float): El valor actual de epsilon.
    Returns:
        int: El índice de la acción elegida.
    """
    if random.random() < current_epsilon:
        # Exploración: elige una acción aleatoria
        return random.choice(range(NUM_ACTIONS))
    else:
        # Explotación: elige la mejor acción según Q-table
        q_values = current_q_table[state]
        # Manejo de empates: selecciona aleatoriamente entre las mejores acciones
        best_value = np.max(q_values)
        # Evita error si todos los Q-values son iguales (ej. al inicio)
        if np.all(q_values == best_value):
             return random.choice(range(NUM_ACTIONS))
        else:
            best_actions = [i for i, v in enumerate(q_values) if v == best_value]
            return random.choice(best_actions)


def run_sarsa(num_episodes, q_table_to_modify, alpha, gamma, epsilon):
    """
    Ejecuta el bucle de aprendizaje de SARSA.
    Args:
        num_episodes (int): Número de episodios para entrenar.
        q_table_to_modify (defaultdict): La tabla Q a modificar durante el aprendizaje.
        alpha (float): Tasa de aprendizaje.
        gamma (float): Factor de descuento.
        epsilon (float): Probabilidad de exploración.
    Returns:
        tuple: (list, list)
               steps_per_episode: Una lista con el número de pasos tomados en cada episodio.
               episode_time_steps: Una lista con el paso de tiempo acumulado al final de cada episodio.
    """
    steps_per_episode = []
    total_time_steps = 0
    episode_time_steps = [] # Para graficar como en el libro (Episodios vs Pasos de tiempo)

    print(f"Iniciando entrenamiento SARSA por {num_episodes} episodios...")
    print(f"Parámetros: alpha={alpha}, gamma={gamma}, epsilon={epsilon}")

    for episode in range(num_episodes):
        state = START_STATE
        # Pasa la tabla Q actual y epsilon a choose_action
        action = choose_action(state, q_table_to_modify, epsilon)
        done = False
        steps = 0

        while not done:
            next_state, reward, done = env_step(state, action)
            # Pasa la tabla Q actual y epsilon a choose_action
            next_action = choose_action(next_state, q_table_to_modify, epsilon) # aqui se aplica SARSA, es lo mas relevante

            # Actualización de SARSA
            current_q = q_table_to_modify[state][action]
            # El valor Q del estado terminal es 0
            next_q = q_table_to_modify[next_state][next_action] if not done else 0
            td_target = reward + gamma * next_q
            td_error = td_target - current_q
            q_table_to_modify[state][action] += alpha * td_error

            state = next_state
            action = next_action
            steps += 1
            total_time_steps += 1

            # Control de seguridad
            if steps > GRID_HEIGHT * GRID_WIDTH * 20: # Aumentado límite por si acaso
                 print(f"Episodio {episode+1} excedió el límite de pasos ({steps}), terminando.")
                 done = True

        steps_per_episode.append(steps)
        episode_time_steps.append(total_time_steps) # Guarda el paso de tiempo al final del episodio

        # Imprime progreso ocasionalmente
        if (episode + 1) % 10 == 0 or episode == num_episodes - 1:
            avg_steps = np.mean(steps_per_episode[max(0, episode-9):episode+1]) # Media de los últimos 10 o menos
            print(f"Episodio {episode+1}/{num_episodes} completado. Pasos: {steps}. Pasos promedio (últimos <=10): {avg_steps:.2f}. Pasos de tiempo totales: {total_time_steps}")


    print("Entrenamiento completado.")
    return steps_per_episode, episode_time_steps


def get_greedy_path(current_q_table):
    """
    Obtiene la trayectoria seguida por una política puramente greedy
    basada en la Q-table aprendida.
    Args:
        current_q_table (defaultdict): La tabla Q aprendida.
    Returns:
        list: Lista de tuplas (estado, acción) representando la trayectoria.
              Retorna None si no se puede alcanzar la meta o hay un bucle.
    """
    path = []
    state = START_STATE
    visited = set() # Para detectar bucles
    steps = 0
    max_steps = GRID_HEIGHT * GRID_WIDTH * 2 # Límite de seguridad

    while state != GOAL_STATE and steps < max_steps:
        if state in visited:
            print("¡Bucle detectado en la trayectoria greedy!")
            return None
        visited.add(state)

        q_values = current_q_table[state]
        # Elige la primera mejor acción encontrada (podría haber empates)
        # Si todos los valores son iguales (ej. estado no explorado), elige aleatorio
        if np.all(q_values == q_values[0]):
            action = random.choice(range(NUM_ACTIONS))
        else:
            action = np.argmax(q_values)

        path.append((state, action))
        next_state, _, done = env_step(state, action)
        state = next_state
        steps += 1
        if done and state != GOAL_STATE:
             print("Error: Estado 'done' alcanzado sin estar en la meta.")
             return None

    if state == GOAL_STATE:
        path.append((state, -1)) # -1 indica sin acción en el estado final
        return path
    else:
        print(f"No se pudo alcanzar la meta con la política greedy después de {steps} pasos.")
        return None

# --- Configuración y Ejecución ---
if __name__ == "__main__":
    # Parámetros de entrenamiento
    NUM_TRAINING_EPISODES = 170 # Ajusta según sea necesario

    # entrenamiento SARSA (modifica la tabla Q global)
    steps_history, time_step_history = run_sarsa(NUM_TRAINING_EPISODES, q_table, ALPHA, GAMMA, EPSILON)

    # --- Resultados del Aprendizaje ---

    # 1. Gráfica de Episodios vs Pasos de Tiempo (como en el libro)
    plt.figure(figsize=(10, 6))
    plt.plot(time_step_history, range(1, NUM_TRAINING_EPISODES + 1), color='red', marker='.', linestyle='-')
    plt.title('Progreso del Aprendizaje SARSA (Episodios vs. Pasos de Tiempo)')
    plt.xlabel('Pasos de Tiempo Acumulados')
    plt.ylabel('Episodios Completados')
    plt.grid(True)
    plt.xlim(left=0)
    plt.ylim(bottom=0)
    plt.show()

    # 2. Gráfica de Pasos por Episodio
    plt.figure(figsize=(10, 6))
    plt.plot(steps_history, label='Pasos por Episodio')
    # Calcular una media móvil para suavizar
    window_size = 10
    if len(steps_history) >= window_size:
        moving_avg = np.convolve(steps_history, np.ones(window_size)/window_size, mode='valid')
        plt.plot(np.arange(window_size - 1, len(steps_history)), moving_avg, label=f'Media Móvil ({window_size} episodios)', color='red', linewidth=2)
    plt.title('Pasos por Episodio durante el Entrenamiento SARSA')
    plt.xlabel('Episodio')
    plt.ylabel('Número de Pasos')
    plt.grid(True)
    plt.legend()
    plt.show()

    # --- Mostrar la Trayectoria Óptima Encontrada ---
    print("\nCalculando la trayectoria greedy encontrada...")
    # Pasa la tabla Q global aprendida a get_greedy_path
    greedy_path = get_greedy_path(q_table)

    if greedy_path:
        print("Trayectoria Greedy:")
        path_coords = [p[0] for p in greedy_path]
        print(path_coords)
        print(f"Longitud de la trayectoria: {len(path_coords) - 1} pasos")

        # Visualizar la trayectoria en la cuadrícula
        grid_viz = np.full((GRID_HEIGHT, GRID_WIDTH), '.', dtype=str)
        grid_viz[START_STATE] = 'S'
        grid_viz[GOAL_STATE] = 'G'
        action_symbols = {0: '^', 1: 'v', 2: '<', 3: '>'}

        for i, (state, action) in enumerate(greedy_path[:-1]): # Excluye el estado final
            r, c = state
            if grid_viz[r, c] not in ('S', 'G'):
                 grid_viz[r, c] = '*' # Marca el camino

        print("\nVisualización de la Trayectoria Greedy:")
        grid_viz[START_STATE] = 'S' # Asegura que S y G no se sobrescriban
        grid_viz[GOAL_STATE] = 'G'
        for r in range(GRID_HEIGHT):
            print(" ".join(grid_viz[r]))
        print("\nFuerza del viento (por columna):")
        print(" ".join(map(str, WIND)))
    else:
        print("No se pudo encontrar una trayectoria completa a la meta.")