# -*- coding: utf-8 -*-
"""q_learning_gridworld_5x5_02.ipynb

Automatically generated by Colab.


"""

# =====================================================================
# Q-Learning
#
# =====================================================================
# Materia: Aprendizaje por Refuerzo I
# Carrera: Maestria en Inteligencia Artificial - Universidad de Buenos Aires
# Año: 2025
# Docente: Miguel Augusto Azar
# =====================================================================

'''

Gridworld 5x5 Q-table 3 dimensiones
===================================



'''
import numpy as np
import random
import matplotlib.pyplot as plt

plt.rcParams.update({
    'figure.facecolor': '#2b2b2b',     # fondo exterior
    'axes.facecolor':   '#2b2b2b',     # fondo del área del gráfico
    'axes.edgecolor':   '#cccccc',     # borde de los ejes
    'axes.labelcolor':  '#cccccc',     # etiquetas de los ejes
    'xtick.color':      '#cccccc',     # color de los números en el eje X
    'ytick.color':      '#cccccc',     # color de los números en el eje Y
    'text.color':       '#cccccc',     # color del título y textos
    'grid.color':       '#444444',     # color de la grilla
})


# hiperparametros
alpha = 0.1  # Tasa de aprendizaje
gamma = 0.9  # Factor de descuento
epsilon = 0.2  # Factor de exploracion
num_episodios = 1000
max_pasos = 100

# configuracon del grid
filas, columnas = 5, 5
estado_meta = (4, 4)
recompensa_meta = 100
recompensa_default = -1
acciones = ['arriba', 'abajo', 'izquierda', 'derecha']

# tabla Q y lista de recompensas
Q = np.zeros((filas, columnas, len(acciones)))
recompensas_totales = []

def elegir_accion(estado):
    if random.uniform(0, 1) < epsilon:
        return random.choice(range(len(acciones)))
    else:
        fila, col = estado
        return np.argmax(Q[fila, col])

def obtener_nuevo_estado(estado, accion):
    fila, col = estado
    if accion == 0 and fila > 0:
        fila -= 1
    elif accion == 1 and fila < filas - 1:
        fila += 1
    elif accion == 2 and col > 0:
        col -= 1
    elif accion == 3 and col < columnas - 1:
        col += 1
    return (fila, col)

# entrenamiento
for episodio in range(num_episodios):
    estado_actual = (0, 0)
    recompensa_total = 0
    for paso in range(max_pasos):
        accion = elegir_accion(estado_actual)
        estado_siguiente = obtener_nuevo_estado(estado_actual, accion)

        # recompensa
        if estado_siguiente == estado_meta:
            recompensa = recompensa_meta
        else:
            recompensa = recompensa_default

        # actualización Q
        fila, col = estado_actual
        fila_sig, col_sig = estado_siguiente
        mejor_Q_siguiente = np.max(Q[fila_sig, col_sig])
        Q[fila, col, accion] = Q[fila, col, accion] + alpha * (recompensa + gamma * mejor_Q_siguiente - Q[fila, col, accion])

        estado_actual = estado_siguiente
        recompensa_total += recompensa

        if estado_actual == estado_meta:
            break

    recompensas_totales.append(recompensa_total)

#  tabla Q final
print("Tabla Q final:")
print(Q)

#  curva de convergencia
plt.plot(recompensas_totales)
plt.title("Curva de convergencia")
plt.xlabel("Episodio")
plt.ylabel("Recompensa total")
plt.grid()
plt.show()

#  política aprendida (flechas)
print("\nPolítica aprendida (flechas):")
for fila in range(filas):
    fila_str = ""
    for col in range(columnas):
        if (fila, col) == estado_meta:
            fila_str += " 🏁 "
        else:
            mejor_accion = np.argmax(Q[fila, col])
            if mejor_accion == 0:
                fila_str += " ↑  "
            elif mejor_accion == 1:
                fila_str += " ↓  "
            elif mejor_accion == 2:
                fila_str += " ←  "
            elif mejor_accion == 3:
                fila_str += " →  "
    print(fila_str)