# -*- coding: utf-8 -*-
"""q_learning_gridworld_5x5_03.ipynb

Automatically generated by Colab.

"""

# =====================================================================
# Q-Learning (algoritmo basico - muestra ademas una matriz de politicas aprendidas)
#
# =====================================================================
# Materia: Aprendizaje por Refuerzo I
# Carrera: Maestria en Inteligencia Artificial - Universidad de Buenos Aires
# Año: 2025
# Docente: Miguel Augusto Azar
# =====================================================================

'''

Gridworld 5x5 - Q-Table 3 dimensiones
=====================================

Política aprendida (flechas):
 ↓   ↓   ↓   →   ↓
 ↓   ↓   ↓   →   ↓
 →   ↓   ↓   →   ↓
 →   →   ↓   ↓   ↓
 →   →   →   →   🏁

'''


import numpy as np
import random

# parametros
alpha = 0.1  # tasa de aprendizaje
gamma = 0.9  # factor de descuento
epsilon = 0.2  # factor de exploracion (probabilidad de tomar accion aleatoria)
num_episodios = 10000  # nmero de episodios de entrenamiento
max_pasos = 100  # maximo de pasos por episodio

# configuración del grid
filas, columnas = 5, 5
estado_meta = (4, 4)  # la meta está en la esquina inferior derecha, sin obstac.
recompensa_meta = 100
recompensa_default = -1  # penaliz. por cada movimiento
acciones = ['arriba', 'abajo', 'izquierda', 'derecha']

# tabla Q
Q = np.zeros((filas, columnas, len(acciones)))

# funcion para elegir la siguiente accion según la politica epsilon-greedy
def elegir_accion(estado):
    if random.uniform(0, 1) < epsilon:
        return random.choice(range(len(acciones)))  # accion aleatoria
    else:
        fila, col = estado
        return np.argmax(Q[fila, col])  # accion con mayor valor Q

# funcinn para obtener el siguiente estado según la accion
def obtener_nuevo_estado(estado, accion):
    fila, col = estado
    if accion == 0 and fila > 0:  # arriba
        fila -= 1
    elif accion == 1 and fila < filas - 1:  # Abajo
        fila += 1
    elif accion == 2 and col > 0:  # izquierda
        col -= 1
    elif accion == 3 and col < columnas - 1:  # derecha
        col += 1
    return (fila, col)

# entrenamiento
for episodio in range(num_episodios):
    estado_actual = (0, 0)  # comienza desde la esquina superior izquierda
    for paso in range(max_pasos):
        accion = elegir_accion(estado_actual)
        estado_siguiente = obtener_nuevo_estado(estado_actual, accion)

        # recompensa
        if estado_siguiente == estado_meta:
            recompensa = recompensa_meta
        else:
            recompensa = recompensa_default

        # actualizacion de la tabla Q
        fila, col = estado_actual
        fila_sig, col_sig = estado_siguiente
        mejor_Q_siguiente = np.max(Q[fila_sig, col_sig])
        Q[fila, col, accion] = Q[fila, col, accion] + alpha * (recompensa + gamma * mejor_Q_siguiente - Q[fila, col, accion])

        estado_actual = estado_siguiente

        # si llega a la meta, termina el episodio
        if estado_actual == estado_meta:
            break

# tabla Q entrenada
print("Tabla Q final:")
print(Q)
print("episodios: ", episodio)

# política aprendida (flechas)
print("\nPolítica aprendida (flechas):")
for fila in range(filas):
    fila_str = ""
    for col in range(columnas):
        if (fila, col) == estado_meta:
            fila_str += " 🏁 "
        else:
            mejor_accion = np.argmax(Q[fila, col])
            if mejor_accion == 0:
                fila_str += " ↑  "
            elif mejor_accion == 1:
                fila_str += " ↓  "
            elif mejor_accion == 2:
                fila_str += " ←  "
            elif mejor_accion == 3:
                fila_str += " →  "
    print(fila_str)