# -*- coding: utf-8 -*-
"""monte_carlo_off_policy_epsilon_greedy_IS_ponderado_01.ipynb

Automatically generated by Colab.


"""

# =====================================================================
# Monte Carlo (MC) Off-Policy con ε-Greedy con IS ponderado
#
# =====================================================================
# _Aprendizaje por Refuerzo I
# _Maestria en Inteligencia Artificial
# _UBA
# _2025
# =====================================================================

'''

Buscador de tesoro en un laberinto
===================================


Dada una cuadricula que representa un laberinto el objetivo es obtener la
politica optima para alcanzar el tesoro partiendo desde A.


+---+---+---+
| A | B | C |  <-- Fila 0
+---+---+---+
| D | E | F |  <-- Fila 1
+---+---+---+
| G | H | I |  <-- Fila 2
+---+---+---+
  ^   ^   ^
Col 0 Col 1 Col 2


Estados: {A, B, C, D, E, F, G, H, I}

Estado Inicial: Siempre empieza en A.

Estados Terminales:

    I (Tesoro): Si llega a I, el episodio termina y recibe una recompensa
                grande (+10).
    F (Trampa): Si llega a F, el episodio termina y recibe una penalización (-5)

Política (π) ε-Greedy

Recompensas (R):

      Entrar en I: +10
      Entrar en F: -5
      Cualquier otro movimiento (o quedarse quieto por chocar): -0.1 (un pequeño
      costo por cada paso/tiempo).

Factor de Descuento: γ = 1.0 (sin descuento, para simplificar). El valor es la
                      suma total de recompensas futuras.


----------------------------------
| A:       | B:       | C:       |
----------------------------------
| D:       | E:       | F (TRAP) |
----------------------------------
| G:       | H:       | I (TRSR) |
----------------------------------


'''

import numpy as np
import random
import collections
from tqdm import tqdm
import matplotlib.pyplot as plt
import matplotlib.patches as patches

# --- configuración del Entorno 3x3 ---
GRID_ROWS = 3
GRID_COLS = 3
START_STATE = (0, 0)    # Celda 'A'
GOAL_STATE = (2, 2)     # Celda 'I' (Meta)
HOLE_STATE = (1, 2)     # Celda 'F' (Agujero/Penalización)
TERMINAL_STATES = {GOAL_STATE, HOLE_STATE}

# recompnsas
REWARD_GOAL = 10.0
REWARD_HOLE = -5.0
REWARD_STEP = -0.1

ACTIONS = {0: 'UP', 1: 'DOWN', 2: 'LEFT', 3: 'RIGHT'}
ACTION_VECTORS = {
    0: (-1, 0), 1: (1, 0), 2: (0, -1), 3: (0, 1)
}
N_ACTIONS = len(ACTIONS)

# --- Parámetros del Algoritmo (Off-Policy MC IS) ---
GAMMA = 1.0          # Factor de descuento
# EPSILON para la POLÍTICA DE COMPORTAMIENTO (behavior policy b)
# EPSILON = 0.1
EPSILON = 0.2 # aumento un poco epsilon para más exploración en off-policy
NUM_EPISODES = 500000 #  numero alto de episodios
MAX_STEPS_PER_EPISODE = GRID_ROWS * GRID_COLS * 3

# --- Funciones Auxiliares ---
def is_valid(state):
    r, c = state
    return 0 <= r < GRID_ROWS and 0 <= c < GRID_COLS

def take_step(state, action):
    if state in TERMINAL_STATES: return state, 0, True
    dr, dc = ACTION_VECTORS[action]
    next_r, next_c = state[0] + dr, state[1] + dc
    next_state = (next_r, next_c)
    if not is_valid(next_state): # Choca con muro
        next_state = state
        reward = REWARD_STEP
        is_terminal = False
    elif next_state == GOAL_STATE:
        reward = REWARD_GOAL; is_terminal = True
    elif next_state == HOLE_STATE:
        reward = REWARD_HOLE; is_terminal = True
    else: # Paso normal
        reward = REWARD_STEP; is_terminal = False
    return next_state, reward, is_terminal

# --- Algoritmo de Control MC Off-Policy con Muestreo por Importancia Ponderado ---

# inicialización
# Q(s, a): Valores Q para la POLÍTICA OBJETIVO (π, greedy)
Q = collections.defaultdict(lambda: np.zeros(N_ACTIONS))
# C(s, a): Suma acumulada de los pesos (ratios IS) para el promedio ponderado de Q
C = collections.defaultdict(float)
# la política objetivo π(s) es implícitamente argmax Q(s, a)
# la política de comportamiento b(s) será ε-greedy respecto a Q

print(f"Ejecutando Control MC Off-Policy (IS Ponderado) por {NUM_EPISODES} episodios...")

# bucle principal de episodios
for episode_num in tqdm(range(NUM_EPISODES)):

    # --- simulacion del Episodio usando la Política de Comportamiento (b) ε-Greedy ---
    episode_history = []
    state = START_STATE
    terminated = False
    steps = 0

    while not terminated and steps < MAX_STEPS_PER_EPISODE:
        # seleccion de accion ε-Greedy (Política de Comportamiento b)
        if random.random() < EPSILON:
            action = random.randrange(N_ACTIONS) # exploracion
        else:
            action = np.argmax(Q[state]) # explotación (greedy respecto a Q)

        # Ejecutar paso en el entorno
        next_state, reward, terminated = take_step(state, action)
        # Guardar (Estado_t, Acción_t, Recompensa_{t+1})
        episode_history.append((state, action, reward))
        state = next_state
        steps += 1

    # --- Actualización de Q usando Muestreo por Importancia Ponderado ---
    G = 0.0 # inicializa retorno
    W = 1.0 # inicializ peso (ratio de importancia acumulado)

    # Bucle hacia atrás a través de los pasos del episodio (t = T-1, T-2, ..., 0)
    for t in range(len(episode_history) - 1, -1, -1):
        state_t, action_t, reward_tp1 = episode_history[t]

        # Calcular el retorno G desde el paso t
        G = GAMMA * G + reward_tp1

        # Actualizar C(s,a) y Q(s,a) usando el retorno G y el peso W actual
        # (Nota: Esta es la fórmula incremental para Weighted Importance Sampling)
        pair = (state_t, action_t)
        C[pair] += W
        # Solo actualiza si C[pair] no es cero para evitar división por cero
        if C[pair] != 0:
            Q[state_t][action_t] += (W / C[pair]) * (G - Q[state_t][action_t])

        # --- Calcular el siguiente Peso W para el paso anterior (t-1) ---

        # Política Objetivo π(action_t | state_t): Probabilidad de tomar action_t en state_t
        # según la política greedy actual basada en Q. Es 1 si action_t es la mejor, 0 si no.
        best_action_target = np.argmax(Q[state_t])
        prob_target = 1.0 if action_t == best_action_target else 0.0

        # Si la política objetivo NUNCA hubiera tomado esta acción (prob_target=0),
        # entonces esta trayectoria ya no es relevante para estimar Q de π.
        # El peso W se vuelve 0 para todos los pasos anteriores.
        if prob_target == 0:
            break # Sal del bucle hacia atrás para este episodio

        # Política de Comportamiento b(action_t | state_t): Probabilidad con ε-Greedy
        best_action_behavior = np.argmax(Q[state_t]) # Reevalúa por si Q cambió
        if action_t == best_action_behavior:
            prob_behavior = 1.0 - EPSILON + (EPSILON / N_ACTIONS)
        else:
            prob_behavior = EPSILON / N_ACTIONS

        # actualiza el peso para el paso anterior t-1
        # W_{t-1} = W_t * ( π(a_t|s_t) / b(a_t|s_t) )
        # Como π(a_t|s_t) es 1 (porque si fuera 0 ya habríamos hecho break),
        # la actualización se simplifica a:
        if prob_behavior == 0: # Evita división por cero (no debería ocurrir con epsilon > 0)
             print(f"Error: Probabilidad cero en política de comportamiento para {pair}")
             W = 0 # O maneja el error como sea apropiado
             break
        else:
             W = W * (1.0 / prob_behavior)

        # Si W se vuelve 0 (por ejemplo, por el break anterior o problemas numéricos),
        # no tiene sentido seguir acumulando.
        if W == 0:
            break


# --- Muestra de Resultados ---
print("\n--- Entrenamiento Completado ---")
print("\nPolítica Óptima Derivada (π*) - Greedy respecto a Q aprendido (Off-Policy):")

# política greedy final a partir de Q aprendido
final_policy = {}
all_states = [(r, c) for r in range(GRID_ROWS) for c in range(GRID_COLS)]
for s in all_states:
    if s not in TERMINAL_STATES:
        final_policy[s] = np.argmax(Q[s])

# --- visualizacion con Matplotlib ---
action_symbols = {0: '^', 1: 'v', 2: '<', 3: '>'}
fig, ax = plt.subplots(figsize=(5.5, 5.5))

# Colores
color_fondo_normal = '0.2'
color_agujero = 'red'
color_meta = 'darkgreen'
color_borde_celda = 'black'
color_lineas_grid = 'royalblue' #
#color_flecha = 'royalblue'
color_flecha = '#6A0DAD'
# #8A2BE2
# #0000FF
# #4B0082
# #6A0DAD
color_fondo_figura_ejes = '0.2'
color_titulo = 'white'

# fnción auxiliar para dibujar base (Adaptada)
def plot_grid_base_updated(ax):
    for r in range(GRID_ROWS):
        for c in range(GRID_COLS):
            state = (r, c)
            color = color_fondo_normal
            text = ""
            text_color = 'lightgrey'
            if state == GOAL_STATE: color = color_meta; text = "I"; text_color = 'white'
            elif state == HOLE_STATE: color = color_agujero; text = "F"; text_color = 'white'
            rect = patches.Rectangle((c, r), 1, 1, linewidth=1, edgecolor=color_borde_celda, facecolor=color, alpha=0.9)
            ax.add_patch(rect)
            if text: ax.text(c + 0.5, r + 0.5, text, ha='center', va='center', color=text_color, weight='bold', fontsize=12)
    ax.set_xticks(np.arange(GRID_COLS + 1), minor=False)
    ax.set_yticks(np.arange(GRID_ROWS + 1), minor=False)
    ax.set_xticklabels([])
    ax.set_yticklabels([])
    ax.grid(True, which='major', color=color_lineas_grid, linewidth=1.5, linestyle='-')
    ax.set_xlim(0, GRID_COLS)
    ax.set_ylim(GRID_ROWS, 0)
    ax.set_aspect('equal', adjustable='box')
    for spine in ax.spines.values(): spine.set_visible(False)

#  colores de fondo
fig.set_facecolor(color_fondo_figura_ejes)
ax.set_facecolor(color_fondo_figura_ejes)

#  la base
plot_grid_base_updated(ax)

#  flechas de política
arrow_params = dict(width=0.08, head_width=0.25, head_length=0.18, fc=color_flecha, ec=color_flecha)
for r in range(GRID_ROWS):
    for c in range(GRID_COLS):
        state = (r, c)
        if state not in TERMINAL_STATES:
            action_idx = final_policy.get(state, -1)
            if action_idx != -1:
                dr, dc = ACTION_VECTORS[action_idx]
                arrow_len_factor = 0.3
                ax.arrow(c + 0.5 - dc*(arrow_len_factor/2), r + 0.5 - dr*(arrow_len_factor/2),
                         dc * arrow_len_factor, dr * arrow_len_factor, **arrow_params)

# ttulo
ax.set_title(f'Política MC Off-Policy IS ponderaado (ε={EPSILON})', color=color_titulo)

plt.tight_layout()
plt.show()