# -*- coding: utf-8 -*-
"""q_learning_vs_sarsa_cliff_walking_01.ipynb

Automatically generated by Colab.


"""

# =====================================================================
# Q-Learning vs. SARSA
#
# =====================================================================
# Materia: Aprendizaje por Refuerzo I
# Carrera: Maestria en Inteligencia Artificial - Universidad de Buenos Aires
# Año: 2025
# Docente: Miguel Augusto Azar
# =====================================================================

'''

Cliff Walking
=============



'''

import numpy as np
import matplotlib.pyplot as plt
from collections import defaultdict
import random
import time
# Importar patches y colores para la visualización
from matplotlib.patches import Patch
from matplotlib.colors import ListedColormap, BoundaryNorm

#tema oscuro para las graficas
plt.rcParams.update({
    'figure.facecolor': '#2b2b2b',     # fondo exterior
    'axes.facecolor':   '#2b2b2b',     # fondo del área del gráfico
    'axes.edgecolor':   '#cccccc',     # borde de los ejes
    'axes.labelcolor':  '#cccccc',     # etiquetas de los ejes
    'xtick.color':      '#cccccc',     # color de los números en el eje X
    'ytick.color':      '#cccccc',     # color de los números en el eje Y
    'text.color':       '#cccccc',     # color del título y textos
    'grid.color':       '#444444',     # color de la grilla
})

# --- Parámetros del Entorno (Cliff Walking) ---
GRID_HEIGHT = 4
GRID_WIDTH = 12
START_STATE = (3, 0) # Fila 3, Columna 0 (abajo a la izquierda)
GOAL_STATE = (3, 11) # Fila 3, Columna 11 (abajo a la derecha)
CLIFF_ROW = 3
CLIFF_COLS = range(1, 11) # Columnas 1 a 10 inclusive en la fila 3

# Acciones: 0: Arriba, 1: Abajo, 2: Izquierda, 3: Derecha
ACTIONS = [(-1, 0), (1, 0), (0, -1), (0, 1)]
NUM_ACTIONS = len(ACTIONS)
REWARD_STEP = -1
REWARD_CLIFF = -100

# --- Parámetros Comunes de los Agentes ---
ALPHA = 0.5 # Tasa de aprendizaje
GAMMA = 1.0 # Factor de descuento
EPSILON = 0.1 # Probabilidad de exploración
NUM_EPISODES = 500

# --- Tablas Q Separadas ---
q_table_sarsa = defaultdict(lambda: np.zeros(NUM_ACTIONS))
q_table_qlearning = defaultdict(lambda: np.zeros(NUM_ACTIONS))

# --- Funciones del Entorno (Sin cambios) ---
def env_step(state, action_index):
    if state == GOAL_STATE: return state, 0, True
    r, c = state
    dr, dc = ACTIONS[action_index]
    next_r, next_c = r + dr, c + dc
    next_r = np.clip(next_r, 0, GRID_HEIGHT - 1)
    next_c = np.clip(next_c, 0, GRID_WIDTH - 1)
    next_state = (int(next_r), int(next_c))
    reward = REWARD_STEP
    done = False
    if next_state[0] == CLIFF_ROW and next_state[1] in CLIFF_COLS:
        reward = REWARD_CLIFF
        next_state = START_STATE
        done = False
    elif next_state == GOAL_STATE:
        done = True
    return next_state, reward, done

# --- Funciones del Agente (Sin cambios) ---
def choose_action(state, current_q_table, current_epsilon):
    if random.random() < current_epsilon:
        return random.choice(range(NUM_ACTIONS))
    else:
        q_values = current_q_table[state]
        if np.all(q_values == q_values[0]): return random.choice(range(NUM_ACTIONS))
        best_actions = np.flatnonzero(q_values == np.max(q_values))
        return random.choice(best_actions)

# --- Función de Aprendizaje Sarsa (Solo prints cambiados) ---
def run_sarsa(num_episodes, q_table_to_modify, alpha, gamma, epsilon):
    episode_rewards = []
    print(f"\nIniciando SARSA por {num_episodes} episodios...")
    print(f"Parámetros: alpha={alpha}, gamma={gamma}, epsilon={epsilon}")
    start_time = time.time()
    for episode in range(num_episodes):
        state = START_STATE
        action = choose_action(state, q_table_to_modify, epsilon)
        done = False
        total_episode_reward = 0
        steps = 0
        max_steps_per_episode = GRID_WIDTH * GRID_HEIGHT * 10 # Ajustar si es necesario
        while not done and steps < max_steps_per_episode:
            next_state, reward, done = env_step(state, action)
            next_action = choose_action(next_state, q_table_to_modify, epsilon)
            current_q = q_table_to_modify[state][action]
            next_q = q_table_to_modify[next_state][next_action] if not done else 0
            td_target = reward + gamma * next_q
            td_error = td_target - current_q
            q_table_to_modify[state][action] += alpha * td_error
            state = next_state
            action = next_action
            total_episode_reward += reward
            steps += 1
        # Comprobar si se excedió el límite de pasos fuera del bucle
        if steps >= max_steps_per_episode:
             print(f"Episodio SARSA {episode+1} alcanzó límite de pasos ({steps}).")
             # Considerar una penalización grande si se excede el límite
             # total_episode_reward -= 200 # Ejemplo de penalización

        episode_rewards.append(total_episode_reward)

        if (episode + 1) % 100 == 0: # Reducir frecuencia de print
             avg_reward = np.mean(episode_rewards[max(0,episode-99):episode+1]) # Media de los últimos 100 o menos
             print(f"... Episodio SARSA {episode+1}/{num_episodes}. Recompensa Promedio (últimos <=100): {avg_reward:.2f}")
    end_time = time.time()
    print(f"Entrenamiento SARSA completado en {end_time - start_time:.2f} segundos.")
    return episode_rewards

# --- Función de Aprendizaje Q-Learning (Solo prints cambiados) ---
def run_q_learning(num_episodes, q_table_to_modify, alpha, gamma, epsilon):
    episode_rewards = []
    print(f"\nIniciando Q-Learning por {num_episodes} episodios...")
    print(f"Parámetros: alpha={alpha}, gamma={gamma}, epsilon={epsilon}")
    start_time = time.time()
    for episode in range(num_episodes):
        state = START_STATE
        done = False
        total_episode_reward = 0
        steps = 0
        max_steps_per_episode = GRID_WIDTH * GRID_HEIGHT * 10 # Ajustar si es necesario
        while not done and steps < max_steps_per_episode:
            action = choose_action(state, q_table_to_modify, epsilon)
            next_state, reward, done = env_step(state, action)
            current_q = q_table_to_modify[state][action]
            max_next_q = np.max(q_table_to_modify[next_state]) if not done else 0
            td_target = reward + gamma * max_next_q
            td_error = td_target - current_q
            q_table_to_modify[state][action] += alpha * td_error
            state = next_state
            total_episode_reward += reward
            steps += 1
        # Comprobar si se excedió el límite de pasos fuera del bucle
        if steps >= max_steps_per_episode:
            print(f"Episodio Q-Learning {episode+1} alcanzó límite de pasos ({steps}).")
            # total_episode_reward -= 200

        episode_rewards.append(total_episode_reward)

        if (episode + 1) % 100 == 0: # Reducir frecuencia de print
            avg_reward = np.mean(episode_rewards[max(0,episode-99):episode+1]) # Media de los últimos 100 o menos
            print(f"... Episodio Q-Learning {episode+1}/{num_episodes}. Recompensa Promedio (últimos <=100): {avg_reward:.2f}")
    end_time = time.time()
    print(f"Entrenamiento Q-Learning completado en {end_time - start_time:.2f} segundos.")
    return episode_rewards

# --- Función para obtener trayectoria (Sin cambios) ---
def get_greedy_path(current_q_table):
    path = []
    state = START_STATE
    steps = 0
    max_steps = GRID_WIDTH * GRID_HEIGHT * 2
    visited_for_path = set()
    while state != GOAL_STATE and steps < max_steps:
        if state in visited_for_path: print("¡Bucle detectado en la trayectoria greedy!"); return None
        visited_for_path.add(state)
        if state[0] == CLIFF_ROW and state[1] in CLIFF_COLS: print("¡Error! La política greedy llevó al acantilado."); return path
        q_values = current_q_table[state]
        if np.all(q_values == q_values[0]): action = random.choice(range(NUM_ACTIONS))
        else: action = np.argmax(q_values)
        path.append((state, action))
        next_state, _, done = env_step(state, action)
        if next_state[0] == CLIFF_ROW and next_state[1] in CLIFF_COLS:
             print(f"La trayectoria greedy lleva al acantilado desde {state} con acción {action}.")
             path.append((next_state, -2))
             return path
        state = next_state
        steps += 1
    if state == GOAL_STATE: path.append((state, -1))
    else: print(f"No se pudo alcanzar la meta con la política greedy después de {steps} pasos."); return None
    return path

# --- FUNCIÓN DE VISUALIZACIÓN (CON DEPURACIÓN Y REFINAMIENTO) ---
def plot_paths_on_grid(sarsa_path_states, qlearning_path_states):
    """Visualiza las trayectorias de Sarsa y Q-Learning en la cuadrícula """
    print("-" * 20)
    print("Visualizando Trayectorias:")
    print("SARSA Coords:", sarsa_path_states) # PRINT DE DEPURACIÓN
    print("Q-Learning Coords:", qlearning_path_states) # PRINT DE DEPURACIÓN
    print("-" * 20)

    # Asegurarse de que las entradas son listas, incluso si son None
    sarsa_coords = sarsa_path_states if sarsa_path_states is not None else []
    qlearning_coords = qlearning_path_states if qlearning_path_states is not None else []

    # Crear matriz base: 0 = Vacío, 1 = Acantilado
    grid_data = np.zeros((GRID_HEIGHT, GRID_WIDTH), dtype=int)
    for c in CLIFF_COLS:
        grid_data[CLIFF_ROW, c] = 1 # Marcar acantilado

    # Marcar caminos: 2 = Solo Sarsa, 3 = Solo Q-Learning, 4 = Ambos
    path_values = {'sarsa': 2, 'qlearning': 3, 'both': 4}

    # print("Marcando camino SARSA...") # Descomentar si es necesario
    if sarsa_coords: # Solo si la lista no está vacía
        for state in sarsa_coords:
             # Asegurarse de que state sea una tupla de enteros
             r, c = int(state[0]), int(state[1])
             if 0 <= r < GRID_HEIGHT and 0 <= c < GRID_WIDTH: # Doble chequeo de límites
                 if grid_data[r, c] == 0: # Si está vacío
                     grid_data[r, c] = path_values['sarsa']
                     # print(f"  SARSA marcado en ({r},{c})") # Descomentar para depuración detallada
                 # No sobrescribir acantilado, inicio o meta si ya estuvieran marcados con otros valores
                 elif grid_data[r, c] == 1: # No sobrescribir acantilado
                     pass
                 # else: print(f"  SARSA no marcó ({r},{c}), valor actual: {grid_data[r,c]}") # Depuración
             else:
                 print(f"Advertencia: Coordenada SARSA fuera de límites: {(r, c)}")

    # print("Marcando camino Q-Learning...") # Descomentar si es necesario
    if qlearning_coords: # Solo si la lista no está vacía
        for state in qlearning_coords:
            r, c = int(state[0]), int(state[1])
            if 0 <= r < GRID_HEIGHT and 0 <= c < GRID_WIDTH:
                if grid_data[r, c] == path_values['sarsa']: # Si Sarsa ya pasó por aquí
                    grid_data[r, c] = path_values['both']
                    # print(f"  Ambos marcados en ({r},{c})")
                elif grid_data[r, c] == 0: # Si estaba vacío
                    grid_data[r, c] = path_values['qlearning']
                    # print(f"  Q-Learning marcado en ({r},{c})")
                elif grid_data[r, c] == 1: # No sobrescribir acantilado
                     pass
                # else: print(f"  Q-L no marcó ({r},{c}), valor actual: {grid_data[r,c]}") # Depuración
            else:
                 print(f"Advertencia: Coordenada Q-Learning fuera de límites: {(r, c)}")


    # Marcar inicio y meta: 5 = Inicio, 6 = Meta (sobrescriben caminos si es necesario)
    # Asegurarse de que START_STATE y GOAL_STATE sean tuplas de enteros
    start_r, start_c = int(START_STATE[0]), int(START_STATE[1])
    goal_r, goal_c = int(GOAL_STATE[0]), int(GOAL_STATE[1])
    grid_data[start_r, start_c] = 5
    grid_data[goal_r, goal_c] = 6

    # --- Impresión de depuración de la matriz numérica ---
    print("\nMatriz numérica para visualización (grid_data):")
    print(grid_data)
    print("-" * 20)
    # --- Fin de la impresión de depuración ---

    # Definir mapa de colores y límites (sin cambios)
    cmap = ListedColormap(['white', 'dimgrey', 'lightblue', 'lightcoral', 'mediumpurple', 'limegreen', 'gold'])
    bounds = [-0.5, 0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5]
    norm = BoundaryNorm(bounds, cmap.N)

    # --- Creación de la Gráfica Matplotlib (sin cambios) ---
    fig, ax = plt.subplots(figsize=(10, 3.5))
    cax = ax.imshow(grid_data, cmap=cmap, norm=norm, interpolation='nearest', origin='upper')
    ax.set_xticks(np.arange(GRID_WIDTH))
    ax.set_yticks(np.arange(GRID_HEIGHT))
    ax.set_xticklabels([])
    ax.set_yticklabels([])
    ax.set_xticks(np.arange(-.5, GRID_WIDTH, 1), minor=True)
    ax.set_yticks(np.arange(-.5, GRID_HEIGHT, 1), minor=True)
    ax.grid(which='minor', color='black', linestyle='-', linewidth=1)
    ax.tick_params(which='major', bottom=False, left=False)
    ax.text(start_c, start_r, ' S', ha='center', va='center', color='white', fontsize=10, fontweight='bold')
    ax.text(goal_c, goal_r, ' G', ha='center', va='center', color='black', fontsize=10, fontweight='bold')
    cliff_center_col = (CLIFF_COLS[0] + CLIFF_COLS[-1]) / 2
    ax.text(cliff_center_col, CLIFF_ROW, 'The Cliff', ha='center', va='center', color='white', fontsize=9)
    legend_elements = [Patch(facecolor='white', edgecolor='k', label='Safe Zone'), Patch(facecolor='dimgrey', edgecolor='k', label='Cliff'), Patch(facecolor='lightblue', edgecolor='k', label='Sarsa Path'), Patch(facecolor='lightcoral', edgecolor='k', label='Q-Learning Path'), Patch(facecolor='mediumpurple', edgecolor='k', label='Overlap'), Patch(facecolor='limegreen', edgecolor='k', label='Start (S)'), Patch(facecolor='gold', edgecolor='k', label='Goal (G)')]
    ax.legend(handles=legend_elements, bbox_to_anchor=(1.01, 1), loc='upper left', fontsize='small')
    ax.set_title('Learned Greedy Paths')
    plt.tight_layout(rect=[0, 0, 0.82, 1])
    plt.show()


# --- Ejecución Principal (Sin cambios) ---
if __name__ == "__main__":
    # Ejecutar ambos algoritmos
    sarsa_rewards = run_sarsa(NUM_EPISODES, q_table_sarsa, ALPHA, GAMMA, EPSILON)
    qlearning_rewards = run_q_learning(NUM_EPISODES, q_table_qlearning, ALPHA, GAMMA, EPSILON)

    # --- Graficar Resultados Comparativos de Recompensas  ---
    plt.figure(figsize=(12, 7))
    window_size = 60
    sarsa_moving_avg = np.convolve(sarsa_rewards, np.ones(window_size)/window_size, mode='valid')
    q_moving_avg = np.convolve(qlearning_rewards, np.ones(window_size)/window_size, mode='valid')
    x_axis_avg = np.arange(window_size - 1, NUM_EPISODES)
    plt.plot(sarsa_rewards, alpha=0.2, color='blue', label='Sarsa (Episode Reward)')
    plt.plot(qlearning_rewards, alpha=0.2, color='red', label='Q-Learning (Episode Reward)')
    plt.plot(x_axis_avg, sarsa_moving_avg, color='blue', linewidth=2.5, label=f'Sarsa (Moving Avg {window_size})')
    plt.plot(x_axis_avg, q_moving_avg, color='red', linewidth=2.5, label=f'Q-Learning (Moving Avg {window_size})')
    plt.title('Sarsa vs. Q-Learning Performance on Cliff Walking')
    plt.xlabel('Episodes')
    plt.ylabel('Sum of rewards during episode')
    plt.ylim(-100, -10)
    plt.legend(loc='lower right')
    plt.grid(True)
    plt.tight_layout()
    plt.show()

    # --- Obtener y Visualizar Trayectorias ---
    print("\nCalculating SARSA greedy path...")
    sarsa_path = get_greedy_path(q_table_sarsa)
    # Asegurarse de pasar una lista de coordenadas (o lista vacía) a la función de plot
    sarsa_path_coords = [p[0] for p in sarsa_path] if sarsa_path else [] # Usar [] si es None
    if sarsa_path:
        print("SARSA Path (States):", sarsa_path_coords)
        print(f"Length: {len(sarsa_path) - 1} steps")
    else:
        print("SARSA path not found or incomplete.") # Mensaje si falla

    print("\nCalculating Q-Learning greedy path...")
    q_path = get_greedy_path(q_table_qlearning)
    q_path_coords = [p[0] for p in q_path] if q_path else [] # Usar [] si es None
    if q_path:
        print("Q-Learning Path (States):", q_path_coords)
        print(f"Length: {len(q_path) - 1} steps")
    else:
        print("Q-Learning path not found or incomplete.") # Mensaje si falla

    # Llamar a la función de visualización actualizada
    # Se llamará incluso si una trayectoria es vacía, para mostrar la otra
    print("\nGenerating grid path visualization...")
    plot_paths_on_grid(sarsa_path_coords, q_path_coords)