# -*- coding: utf-8 -*-
"""monte_carlo_ES_control_01.ipynb

Automatically generated by Colab.


"""

# =====================================================================
# Algoritmo de Control Montecarlo con Primera Visita
#
# =====================================================================
# _Aprendizaje por Refuerzo I
# _Maestria en Inteligencia Artificial
# _UBA
# _2025
# =====================================================================

'''

Robot limpiador de un parque
 _________
|_|_|_|_|_|
|_|_|_|_|_|
|_|_|_|_|_|
|_|_|_|_|_|
|_|_|_|_|_|<--Contenedor

'''

import numpy as np
import random
import collections
from tqdm import tqdm
# Importar matplotlib
import matplotlib.pyplot as plt
import matplotlib.patches as patches # Para dibujar rectángulos de fondo

# --- Configuración del Entorno REDUCIDO ---
GRID_ROWS = 5 # Reducido
GRID_COLS = 5 # Reducido
CONTAINER_POS = (4, 4) # Celda objetivo (contenedor)

#  obstáculos (lista de tuplas (fila, columna)) - Ajustados al grid 5x5
OBSTACLES = [
    (1, 1), (1, 2), (1, 3), # Fila superior de obstaculos
    (2, 1),                 # Columna izquierda de obstaculos
    (3, 1), (3, 3)          # Obstaculos inferiores
]
OBSTACLE_SET = set(OBSTACLES) # mas eficiente para búsquedas

ACTIONS = {0: 'UP', 1: 'DOWN', 2: 'LEFT', 3: 'RIGHT'}
ACTION_VECTORS = { # Cambios en (dr, dc) para cada acción
    0: (-1, 0), # UP
    1: (1, 0),  # DOWN
    2: (0, -1), # LEFT
    3: (0, 1)   # RIGHT
}
N_ACTIONS = len(ACTIONS)

# --- Parámetros MC ES ---
GAMMA = 1.0
NUM_EPISODES = 500000
MAX_STEPS_PER_EPISODE = GRID_ROWS * GRID_COLS * 2 # Límite ajustado

# --- Funciones Auxiliares ---
def is_valid(state):
    """Comprueba si el estado está dentro de los límites del grid."""
    r, c = state
    return 0 <= r < GRID_ROWS and 0 <= c < GRID_COLS


def take_step(state, action):
    """
    Simula un paso en el entorno.
    Devuelve (next_state, reward, is_terminal).
    """
    if state == CONTAINER_POS:
        return state, 0, True #  está en el terminal

    dr, dc = ACTION_VECTORS[action]
    next_r, next_c = state[0] + dr, state[1] + dc
    next_state = (next_r, next_c)

    #  límites y obstáculos
    if not is_valid(next_state) or next_state in OBSTACLE_SET:
        next_state = state # Chocó, se queda en el mismo lugar
        reward = -1 # Penalización por intentar moverse (y chocar)
        is_terminal = False
    elif next_state == CONTAINER_POS:
        reward = 2 # Recompensa por llegar
        is_terminal = True
    else:
        reward = -0.1 # Costo de dar un paso válido
        is_terminal = False

    return next_state, reward, is_terminal

# --- Algoritmo Monte Carlo ES (Control) ---

# 1. Inicialización
Q = collections.defaultdict(lambda: np.zeros(N_ACTIONS))
policy = collections.defaultdict(lambda: random.randint(0, N_ACTIONS - 1)) # Política inicial aleatoria
returns_sum = collections.defaultdict(float)
returns_count = collections.defaultdict(float)

#  estados válidos para los Inicios Exploratorios
valid_start_states = []
for r in range(GRID_ROWS):
    for c in range(GRID_COLS):
        state = (r, c)
        if state != CONTAINER_POS and state not in OBSTACLE_SET:
            valid_start_states.append(state)
if not valid_start_states:
    raise ValueError("No valid start states found. Check obstacle/container placement.")

print(f"Ejecutando Control Monte Carlo ES (Grid 5x5) por {NUM_EPISODES} episodios...")

# 2. Bucle por cada episodio
for episode_num in tqdm(range(NUM_EPISODES)):
    start_state = random.choice(valid_start_states)
    start_action = random.randrange(N_ACTIONS)
    current_state, reward, terminated = take_step(start_state, start_action)
    episode_history = [(start_state, start_action, reward)]
    steps = 1
    while not terminated and steps < MAX_STEPS_PER_EPISODE:
        current_action = policy[current_state]
        next_state, reward, terminated = take_step(current_state, current_action)
        episode_history.append((current_state, current_action, reward))
        current_state = next_state
        steps += 1
    G = 0
    pairs_visited_in_episode = set()
    for t in range(len(episode_history) - 1, -1, -1):
        state_t, action_t, reward_tp1 = episode_history[t]
        G = GAMMA * G + reward_tp1
        pair = (state_t, action_t)
        if pair not in pairs_visited_in_episode:
            returns_sum[pair] += G
            returns_count[pair] += 1
            if returns_count[pair] > 0:
                 Q[state_t][action_t] = returns_sum[pair] / returns_count[pair]
            policy[state_t] = np.argmax(Q[state_t]) # Mejora de Política
            pairs_visited_in_episode.add(pair)

# --- Muestra de Resultados    ---
print("\n--- Entrenamiento Completado ---")
print("Generando visualizaciones con Matplotlib...")

# --- Función para graficar la cuadrícula base  ---
def plot_grid_base(ax):
    #   colores
    color_cesped = 'forestgreen'
    color_obstaculo = 'dimgray'
    color_contenedor = 'white'
    color_borde_celda = 'black'

    for r in range(GRID_ROWS):
        for c in range(GRID_COLS):
            state = (r, c)
            color = color_cesped
            if state == CONTAINER_POS:
                color = color_contenedor
            elif state in OBSTACLE_SET:
                color = color_obstaculo
            # rectángulo de la celda
            rect = patches.Rectangle((c, r), 1, 1, linewidth=1, edgecolor=color_borde_celda, facecolor=color, alpha=0.8)
            ax.add_patch(rect)

    # Configuración estándar de los ejes para la cuadrícula
    ax.set_xticks(np.arange(GRID_COLS + 1), minor=False)
    ax.set_yticks(np.arange(GRID_ROWS + 1), minor=False)
    ax.set_xticklabels([])
    ax.set_yticklabels([])
    ax.grid(True, which='major', color=color_borde_celda, linewidth=1.5)
    ax.set_xlim(0, GRID_COLS)
    ax.set_ylim(GRID_ROWS, 0) # Origen (0,0) arriba a la izquierda
    ax.set_aspect('equal', adjustable='box')

# colores para los elementos fuera de la cuadrícula
color_borde_y_fondo_ejes = '0.2'
color_texto_q = 'lightgrey'
color_titulo = 'white'

# --- Gráfico 1: Valores Q (Valor del Estado) ---
fig_q, ax_q = plt.subplots(figsize=(7, 7), facecolor=color_borde_y_fondo_ejes)
ax_q.set_facecolor(color_borde_y_fondo_ejes)
plot_grid_base(ax_q) # Dibuja celdas (cesped/obstaculo/contenedor)

# Añade texto de valores Q
for r in range(GRID_ROWS):
    for c in range(GRID_COLS):
        state = (r, c)
        if state != CONTAINER_POS and state not in OBSTACLE_SET:
            state_value = np.max(Q.get(state, np.zeros(N_ACTIONS)))
            # Usa color de texto gris claro
            ax_q.text(c + 0.5, r + 0.5, f"{state_value:.1f}",
                      ha='center', va='center', color=color_texto_q, fontsize=8, weight='bold')

ax_q.set_title('Valor del Estado V(s) = max_a Q(s,a)', color=color_titulo)
plt.tight_layout() # Ajusta el layout

# --- Gráfico 2: Política Óptima (Flechas) ---
fig_pi, ax_pi = plt.subplots(figsize=(7, 7), facecolor=color_borde_y_fondo_ejes)
ax_pi.set_facecolor(color_borde_y_fondo_ejes)
plot_grid_base(ax_pi) # dibuja celdas (cesped/obstaculo/contenedor)

# flechas amarillas
arrow_params = dict(width=0.1, head_width=0.3, head_length=0.2, fc='yellow', ec='yellow')
for r in range(GRID_ROWS):
    for c in range(GRID_COLS):
        state = (r, c)
        if state != CONTAINER_POS and state not in OBSTACLE_SET and state in policy:
            action_idx = policy[state]
            dr, dc = ACTION_VECTORS[action_idx]
            arrow_len_factor = 0.35
            ax_pi.arrow(c + 0.5 - dc*(arrow_len_factor/2),
                        r + 0.5 - dr*(arrow_len_factor/2),
                        dc * arrow_len_factor, # dx
                        dr * arrow_len_factor, # dy
                        **arrow_params)

ax_pi.set_title('Política Óptima Aprendida (π)', color=color_titulo)
plt.tight_layout() # Ajusta el layout

print("\nVisualizaciones generadas.")
#  gráficos generados
plt.show()