# -*- coding: utf-8 -*-
"""golf_buggy_v0.0.3.ipynb

Automatically generated by Colab.

"""

# =====================================================================
# Q-Learning (ejemplo)
#
# =====================================================================
# Materia: Aprendizaje por Refuerzo I
# Carrera: Maestria en Inteligencia Artificial - Universidad de Buenos Aires
# Año: 2025
# Docente: Miguel Augusto Azar
# =====================================================================

'''

Golf Buggy v.0.0.3
==================

Algoritmo que utiliza Q-Learning para lo siguiente:
===================================================

. Consiste en la simulacion de un carrito de golf que debe moverse desde un punto
de partida (Tee, 'T') hasta un punto de destino (Green, 'G') a través de un
entorno cuadriculado de 8x8.
. El carrito puede moverse en 4 direcciones (acciones): arriba, abajo, izquierda
y derecha.
. El carrito puede transportar de 1 a 4 personas.

El entorno contiene obstáculos:
. H (Colina): Pendientes que el carrito debe atravesar o evitar.
. B (Búnker): Trampas de arena comunes en los campos de golf.

Estructura de recompensas/penalizaciones
========================================

. Búnker (B): Independientemente del número de personas transportadas, si el
carrito choca contra un búnker de arena (B), recibe una penalización de -100 y
el intento actual (episodio) finaliza inmediatamente.
. Terreno Normal: Por cada paso que el carrito da sobre una casilla despejada
(no 'H' ni 'B'), recibe una puntuación de -1 (un pequeño costo de movimiento).
. Pendiente (H): Si el buggy sube a una pendiente (H), recibe una penalización
calculada como -(1.5 ^ numero_de_personas). Esto representa el aumento del
coste/desgaste energético al subir la pendiente, que aumenta con el número de
pasajeros.
. Objetivo (G): Si el carrito llega al destino (G), recibe una recompensa
calculada como (4 * numero_de_personas). Esta estructura de recompensas
incentiva el transporte del máximo número posible de personas hasta el objetivo.

Resultado
=========

Tras el proceso de entrenamiento, el algoritmo genera:
. La ruta óptima encontrada (mostrada como una matriz cuadradaa con flechas:
↑↓←→ que indican la política).
. El número óptimo de personas que el carrito debe transportar para obtener la
máxima recompensa acumulada posible según la política aprendida.
. Una animación que visualiza al agente (carrito) navegando por la ruta óptima
dentro del entorno.

Personalización
===============

El usuario puede modificar el entorno añadiendo o eliminando obstáculos ('H',
'B') dentro de la definición de la matriz del entorno en el código. También
puede modificar las posiciones de los puntos de inicio ('T') y de destino ('G').

///////////////////////////////////////////////////////////////////////////////

Algorithm using Q-Learning for the following:

This simulates a golf buggy that must move from a starting point (Tee, 'T') to
a destination point (Green, 'G') across an 8x8 gridworld environment.
The buggy can move in the 4 directions (actions): up, down, left, and right.
The environment contains obstacles:
    H (Hill): Slopes that the buggy must either traverse or avoid.
    B (Bunker): Sand traps commonly found on golf courses.
The buggy can transport between 1 and 4 people.
Reward/Penalty Structure:
    Bunker (B): Regardless of the number of people being transported, if the
    buggy hits a sand bunker (B), it receives a penalty of -100, and the current
    attempt (episode) ends immediately.
    Normal Terrain: For each step the buggy takes onto a clear square (not 'H'
    or 'B'), it receives a score of -1 (a small cost for movement).
    Hill (H): If the buggy moves onto a hill (H), it receives a penalty
    calculated as -(1.5 to the power of number_of_people). This represents the
    increased energy cost/wear for climbing the slope, scaling with the number
    of passengers.
    Goal (G): If the buggy successfully reaches the destination (G), it receives
    a reward calculated as (4 * number_of_people). This reward structure
    incentivizes transporting the maximum possible number of people to the goal.
Output:
After the training process, the algorithm outputs:
    The optimal path found (displayed as a grid matrix with arrows: ↑↓←→
    indicating the policy).
    The optimal number of people the buggy should carry to achieve the maximum
    possible cumulative reward based on the learned policy.
    An animation visualizing the agent (buggy) navigating the optimal path
    within the environment.
Customization:
The user can alter the environment by adding or removing obstacles ('H', 'B')
within the environment matrix definition in the code. The user can also modify
the positions of the start ('T') and destination ('G') points.

'''

# Ensure tqdm and Pillow are installed
!pip install tqdm pillow

from tqdm import tqdm
import numpy as np
import random
import time
import os
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from matplotlib.animation import FuncAnimation, PillowWriter # Import PillowWriter
from IPython.display import HTML, display # Needed for displaying animation in Colab/Jupyter

# --- Image Loading ---
try:
    image_map = {
        'G': mpimg.imread('green_64.png'),
        'T': mpimg.imread('tee_64.png'),
        'H': mpimg.imread('hill_64.png'),
        'B': mpimg.imread('bunker_64.png'),
        '': mpimg.imread('rough_64.png')
    }

    agent_images = {
        '': mpimg.imread('buggy_rough_64.png'),
        'H': mpimg.imread('buggy_hill_64.png')
    }
except FileNotFoundError as e:
    print(f"Error loading image: {e}")
    print("Please ensure the required PNG files are accessible.")
    exit()
# --- End Image Loading ---


# --- Animation Function ---
def animate_path(environment, path_coords, delay=300, bg_color='#404040'):
    if not path_coords:
        print("Warning: Cannot animate an empty path.")
        return None
    rows, cols = len(environment), len(environment[0])
    fig, ax = plt.subplots(figsize=(cols * 0.7, rows * 0.7))
    fig.patch.set_facecolor(bg_color)
    ax.set_facecolor(bg_color)

    fig.subplots_adjust(left=0.01, right=0.99, bottom=0.01, top=0.99)

    ax.set_xticks([])
    ax.set_yticks([])
    ax.set_xlim(0, cols)
    ax.set_ylim(0, rows)
    ax.set_aspect('equal', adjustable='box')
    ax.axis('off')
    for i in range(rows):
        for j in range(cols):
            cell = environment[i][j]
            img = image_map.get(cell, image_map[''])
            ax.imshow(img, extent=(j, j + 1, rows - i - 1, rows - i))
    start_i, start_j = path_coords[0]
    start_cell = environment[start_i][start_j]
    start_buggy_img = agent_images['H'] if start_cell == 'H' else agent_images['']
    buggy_im = ax.imshow(start_buggy_img, extent=(start_j, start_j + 1, rows - start_i - 1, rows - start_i))
    def update(frame_index):
        i, j = path_coords[frame_index]
        cell = environment[i][j]
        current_buggy_img = agent_images['H'] if cell == 'H' else agent_images['']
        buggy_im.set_data(current_buggy_img)
        buggy_im.set_extent((j, j + 1, rows - i - 1, rows - i))
        return buggy_im,
    anim = FuncAnimation(fig, update, frames=len(path_coords),
                         interval=delay, blit=True, repeat=False)
    plt.close(fig)
    return anim

# --- Environment Definition ---
environment = [
    ['', '',  '',   'H',  '',  '',  '',   ''], # Fila 0
    ['B',  'H',  '',   '',  '',  '',   'H',  ''], # Fila 1
    ['',  '',   'B',   'H',   '', 'H',   'B',  'T'], # Fila 2
    ['',  '',  '',   '',   'H',  '',   'H',  'H'], # Fila 3
    ['H', '',   '',   '',   '', '',  '',   'H'], # Fila 4
    ['',  '',   '',   'B',   'H', 'H',  '',   ''], # Fila 5
    ['',  'B',   'H',  '',   '', '',   '',   ''], # Fila 6
    ['',  'G',   'H',  '',   '',  '',  '',   '']  # Fila 7
]
rows, cols = len(environment), len(environment[0])
actions = ['up', 'down', 'left', 'right']
action_indices = {action: i for i, action in enumerate(actions)}
action_arrows = {'up': '↑', 'down': '↓', 'left': '←', 'right': '→', '': ' '}

# --- Q-learning Parameters ---
alpha = 0.1
gamma = 0.95
initial_epsilon = 1.0
epsilon_decay = 0.999 # Maybe slightly slower decay: 0.9995?
min_epsilon = 0.01
episodes = 2000 # Increase if needed, e.g., 3000 or 5000

# --- Find Start and Goal ---
start = None
goal = None
for i in range(rows):
    for j in range(cols):
        if environment[i][j] == 'T':
            start = (i, j)
        if environment[i][j] == 'G':
            goal = (i, j)
if start is None or goal is None:
    raise ValueError("Start 'T' or Goal 'G' not found in environment")
print(f"Start: {start}, Goal: {goal}")

# --- Q-Learning Training Loop ---
results = []
best_overall_score = -float('inf')
best_policy_info = None
start_time_total = time.time()

for people in range(1, 5):
    print(f"\n--- Training for {people} person(s) ---")
    Q = np.zeros((rows, cols, len(actions)))
    epsilon = initial_epsilon
    start_time_people = time.time()

    for episode in tqdm(range(episodes), desc=f"Episodes ({people} pers.)"):
        state = start
        done = False
        steps = 0
        max_steps_per_episode = rows * cols * 2

        while not done and steps < max_steps_per_episode:
            i, j = state
            if random.uniform(0, 1) < epsilon or np.all(Q[i, j] == 0):
                action_idx = random.randint(0, len(actions) - 1)
            else:
                action_idx = np.argmax(Q[i, j])
            action = actions[action_idx]

            ni, nj = i, j
            if action == 'up' and i > 0: ni -= 1
            elif action == 'down' and i < rows - 1: ni += 1
            elif action == 'left' and j > 0: nj -= 1
            elif action == 'right' and j < cols - 1: nj += 1

            next_state = (ni, nj)
            current_cell = environment[i][j]
            next_cell = environment[ni][nj] if next_state != state else current_cell

            reward = 0
            done = False
            base_cost = -1

            if next_state == state:
                reward = base_cost
                next_q_max = np.max(Q[i, j])
            elif next_cell == 'B':
                reward = -100
                done = True
                next_q_max = 0
            elif next_cell == 'G':
                reward = 4 * people
                done = True
                next_q_max = 0
            elif next_cell == 'H':
                reward = (1.5 ** people) * (-1)
                next_q_max = np.max(Q[ni, nj])
            else: # Rough ''
                reward = base_cost
                next_q_max = np.max(Q[ni, nj])

            old_q_value = Q[i, j, action_idx]
            new_q_value = old_q_value + alpha * (reward + gamma * next_q_max - old_q_value)
            Q[i, j, action_idx] = new_q_value

            if next_state != state:
                 state = next_state
            steps += 1

        epsilon = max(min_epsilon, epsilon * epsilon_decay)

    # --- Evaluation ---
    print(f"Evaluating policy for {people} person(s)...")
    state = start
    path_coords = []
    path_actions = []
    visited_eval = set()
    eval_steps = 0
    eval_limit = rows * cols * 2
    eval_done = False
    final_reward_eval = 0
    reached_goal = False

    while not eval_done and eval_steps < eval_limit:
        i, j = state
        path_coords.append(state) # Append current state

        if state in visited_eval:
            print(f"  Warning: Loop detected at {state} during evaluation.")
            final_reward_eval = -float('inf') # Penalize loops heavily
            break # Exit loop if loop detected
        visited_eval.add(state)

        # Check if current state is goal (e.g., if start == goal)
        # Or if previous step landed on goal (eval_done would be true)
        if state == goal:
             # Should have been caught by eval_done=True in previous step's logic,
             # but handle just in case (e.g., starting at goal)
             if not reached_goal: # Only mark if not already marked
                 reached_goal = True
                 eval_done = True # Ensure loop terminates
             break # Exit if already at goal

        # Choose best action based on Q-table (exploitation)
        if np.all(Q[i, j] == 0):
             print(f"  Warning: Agent stuck at {state} (Q=0). Evaluation failed.")
             final_reward_eval = -float('inf') # Penalize unknown states
             break # Exit loop

        action_idx = np.argmax(Q[i, j])
        action = actions[action_idx]
        path_actions.append(action) # Store action taken FROM current state (i, j)

        # Calculate next state
        ni, nj = i, j
        if action == 'up' and i > 0: ni -= 1
        elif action == 'down' and i < rows - 1: ni += 1
        elif action == 'left' and j > 0: nj -= 1
        elif action == 'right' and j < cols - 1: nj += 1
        next_state = (ni, nj)

        # Calculate reward/cost for LANDING on next_state & check termination
        step_reward = 0
        step_base_cost = -1
        if next_state == state: # Hit wall or invalid move
            step_reward = step_base_cost
            # State remains the same, loop continues
        else:
            # Evaluate the cell we LANDED ON
            next_cell = environment[ni][nj]
            if next_cell == 'B': # Landed on Bunker
                step_reward = -100
                eval_done = True # End evaluation immediately
            elif next_cell == 'G': # Landed on Goal
                step_reward = 4 * people
                eval_done = True # Mark to end evaluation AFTER this step
                reached_goal = True # Mark goal as reached
            elif next_cell == 'H': # Landed on Hill
                step_reward = (1.5 ** people) * (-1)
            else: # Landed on Empty/Rough
                step_reward = step_base_cost

        # Accumulate reward for the step taken
        final_reward_eval += step_reward

        # Update state for the *next* iteration
        # this happens AFTER checking the result of the move
        if next_state != state:
            state = next_state

        eval_steps += 1
        # End of while loop

    # --- Post-evaluation processing ---

    if reached_goal and (not path_coords or path_coords[-1] != goal):
        path_coords.append(goal)
        # Note: path_actions will have one less element than path_coords,
        # because there's no action taken FROM the goal state in a successful path.

    # Check if evaluation ended due to step limit without reaching goal
    if not reached_goal and not eval_done: # eval_done might be true if hit Bunker 'B'
        print(f"  Warning: Step limit ({eval_limit}) reached during evaluation without reaching Goal.")
        # Penalize if didn't reach goal AND didn't hit a bunker
        if state != goal and environment[state[0]][state[1]] != 'B':
             final_reward_eval = -float('inf')
    elif eval_done and not reached_goal:
        # This means eval_done was set (likely hit a Bunker 'B')
        print(f"  Evaluation ended by hitting a non-goal terminal state (e.g., Bunker).")
        # Score already reflects the high penalty from hitting 'B'

    print(f"  Evaluation completed in {eval_steps} steps. Final calculated score: {final_reward_eval:.2f}")
    results.append({'people': people, 'score': final_reward_eval,
                    'path_coords': path_coords, 'path_actions': path_actions,
                    'q_table': Q.copy()})

    # Update best overall policy
    if final_reward_eval > best_overall_score:
        print(f"  >> New best overall score found!")
        best_overall_score = final_reward_eval
        best_policy_info = {'people': people, 'score': final_reward_eval,
                            'path_coords': path_coords, 'path_actions': path_actions,
                            'q_table': Q.copy(), 'reached_goal': reached_goal}

    elapsed_people = time.time() - start_time_people
    print(f"  Time for {people} person(s): {elapsed_people:.2f}s")
# --- End Training Loop ---

# --- Display Final Results ---
print("\n--- Optimal Results ---")
total_elapsed = time.time() - start_time_total
print(f"Total training and evaluation time: {total_elapsed:.2f}s")

if best_policy_info is not None:
    best_people = best_policy_info['people']
    best_score = best_policy_info['score']
    best_path_coords = best_policy_info['path_coords']
    best_path_actions = best_policy_info['path_actions']
    best_reached_goal = best_policy_info['reached_goal']

    print(f"Optimal number of people: {best_people}")
    print(f"Maximum score achieved: {best_score:.2f}")

    if not best_path_coords:
         print("\nOptimal policy resulted in an empty path (likely failed evaluation).")
    elif not best_reached_goal:
         print(f"\nWarning: Optimal policy score ({best_score:.2f}) was highest, but it did not reach the goal 'G'.")
         # Check if path exists before printing
         if best_path_coords:
             print(f"Path taken ({len(best_path_coords)} steps): {best_path_coords}")
         else:
             print("No path coordinates recorded.")
    else:
        # Path exists and goal reached
        print(f"\nOptimal path found ({len(best_path_coords)} steps).") # Length now includes goal


    # Create and print policy map (arrows indicate action FROM cell)
    # This part remains the same, map generation handles path length difference
    arrow_matrix = [[' ' for _ in range(cols)] for _ in range(rows)]
    for r in range(rows):
        for c in range(cols):
            if environment[r][c] == 'B': arrow_matrix[r][c] = 'X'
            elif environment[r][c] == 'H': arrow_matrix[r][c] = 'H'
            elif environment[r][c] == 'T': arrow_matrix[r][c] = 'T'
            elif environment[r][c] == 'G': arrow_matrix[r][c] = 'G'
            elif arrow_matrix[r][c] == ' ': arrow_matrix[r][c] = '.'

    # Draw arrows using the shorter length of path_coords-1 or path_actions
    # path_len = min(len(best_path_coords) -1 if best_reached_goal else len(best_path_coords), len(best_path_actions)) # Corrected calculation
    # Simplified logic: iterate over actions, get corresponding coordinate
    path_len = len(best_path_actions)
    for idx in range(path_len):
         # Check if coordinate exists for this action index
         if idx < len(best_path_coords):
             (r, c) = best_path_coords[idx] # Coord from which action was taken
             action = best_path_actions[idx]
             if arrow_matrix[r][c] not in ('T', 'G', 'X'):
                 arrow_matrix[r][c] = action_arrows.get(action, '?')
         else:
             print(f"Warning: Mismatch between path_coords ({len(best_path_coords)}) and path_actions ({len(best_path_actions)}) length during map drawing.")


    # Ensure Start and Goal are marked correctly regardless of path
    if goal: arrow_matrix[goal[0]][goal[1]] = 'G'
    if start: arrow_matrix[start[0]][start[1]] = 'T'

    print("\nPolicy Map (Path of Best Run):")
    print("  T=Start, G=Goal, H=Hill, X=Bunker, . =Rough")
    print("  Arrows indicate the action taken from that cell in the best path.")
    for row in arrow_matrix:
        print('  ' + ' '.join(f"{cell:1}" for cell in row))

    # --- Generate, Display, and Save Animation ---
    if best_path_coords and best_reached_goal:
        print("\nGenerating animation of the optimal path...")
        anim_delay_ms = 250
        animation_object = animate_path(environment, best_path_coords,
                                        delay=anim_delay_ms, bg_color='#404040')
        if animation_object:
            print("Displaying animation...")
            display(HTML(animation_object.to_jshtml()))
            gif_filename = "golf_buggy_optimal_path.gif"
            print(f"\nSaving animation as {gif_filename}...")
            try:
                fps = 1000 / anim_delay_ms
                writer = PillowWriter(fps=fps)
                animation_object.save(gif_filename, writer=writer)
                print(f"Successfully saved {gif_filename}")
            except Exception as e:
                print(f"Error saving GIF: {e}")
        else:
            print("Failed to create animation object.")
    elif best_path_coords: # Path exists but didn't reach goal
        print("\nNot animating or saving path as it did not reach the goal 'G'.")
    else: # No path found at all for the best score scenario
        print("\nNot animating or saving as no valid path was found for the best policy.")

else:
    print("No successful path to 'G' was found during any evaluation.")
    print("Consider increasing 'episodes', adjusting learning rate 'alpha', discount 'gamma',")
    print("or exploration parameters 'initial_epsilon', 'epsilon_decay'.")