# -*- coding: utf-8 -*-
"""barco_en_oceano_estocastico.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MXPPfcmzxWFngi92I2Lq3e7SBUqjfxmJ
"""

# con entorno estocastico

# iteracion de valor con grafico del entorno

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
import random

# entorno (se agrega la probabilidad de éxito para que sea estocastico)
LADO_OCEANO = 5  # tamaño del océano (cuadrado de 5x5)
MUELLE = (4, 4)  # coordenadas del muelle (fila, columna)
ROCAS = [(1, 1), (2, 3), (3, 1)]  # coordenadas de las rocas
ACCIONES = ['Norte', 'Sur', 'Este', 'Oeste']
RECOMPENSA_MOVIMIENTO = -1
RECOMPENSA_MUELLE = 0
RECOMPENSA_ROCA = -100
FACTOR_DESCUENTO = 0.9
TOLERANCIA = 0.7
P_EXITO = 0.7  # probabilidad de moverse en la dirección deseada


def es_valido(fila, columna):
    """verifica si una celda está dentro de los límites del oceano."""
    return 0 <= fila < LADO_OCEANO and 0 <= columna < LADO_OCEANO


def es_roca(fila, columna):
    """verifica si una celda contiene una roca."""
    return (fila, columna) in ROCAS


def transicion(fila, columna, accion):
    """determina el siguiente estado (celda) dado el estado actual y la accion, considerando el viento."""
    if (fila, columna) == MUELLE:
        return MUELLE  # si ya esta en el muelle, se queda ahi

    # determina la dirección real del movimiento
    direccion_real = accion
    if random.random() > P_EXITO:  # si el viento afecta la direccion
        # elige una direccion perpendicular aleatoria
        direcciones_perpendiculares = []
        if accion in ['Norte', 'Sur']:
            direcciones_perpendiculares = ['Este', 'Oeste']
        else:
            direcciones_perpendiculares = ['Norte', 'Sur']
        direccion_real = random.choice(direcciones_perpendiculares)

    if direccion_real == 'Norte':
        nueva_fila, nueva_columna = fila - 1, columna
    elif direccion_real == 'Sur':
        nueva_fila, nueva_columna = fila + 1, columna
    elif direccion_real == 'Este':
        nueva_fila, nueva_columna = fila, columna + 1
    elif direccion_real == 'Oeste':
        nueva_fila, nueva_columna = fila, columna - 1
    else:
        raise ValueError("Acción inválida")

    if not es_valido(nueva_fila, nueva_columna) or es_roca(nueva_fila, nueva_columna):
        return fila, columna  # permanece en la misma celda si el movimiento no es válido

    return nueva_fila, nueva_columna


def recompensa(fila, columna, accion):
    """Retorna la recompensa para un estado (celda) y accion dados."""
    if (fila, columna) == MUELLE:
        return RECOMPENSA_MUELLE
    nueva_fila, nueva_columna = transicion(fila, columna, accion)
    if es_roca(nueva_fila, nueva_columna):
        return RECOMPENSA_ROCA  # penalizacipn por intentar ir a una roca
    return RECOMPENSA_MOVIMIENTO


def dibujar_entorno(politica, titulo):
    """dibuja el entorno del oceano con las rocas, el muelle y las acciones."""
    mapa = np.zeros((LADO_OCEANO, LADO_OCEANO))  # 0: agua, 1: rocca, 2: muelle
    for fila, columna in ROCAS:
        mapa[fila, columna] = 1
    mapa[MUELLE] = 2

    # define los colores personalizados
    cmap = ListedColormap(['#3CB371', 'black', 'sienna'])
    plt.imshow(mapa, cmap=cmap, origin='lower')

    # inversion del eje y para que coincida con las coordenadas de la matriz
    plt.gca().invert_yaxis()

    # agrega las flechas de la política
    for fila in range(LADO_OCEANO):
        for columna in range(LADO_OCEANO):
            if (fila, columna) not in ROCAS and (fila, columna) != MUELLE:
                accion = politica[(fila, columna)]
                dx, dy = 0, 0
                if accion == 'Norte':
                    dy = -0.3  # inversion dy para el eje y invertido
                elif accion == 'Sur':
                    dy = 0.3  # inversion dy para el eje y invertido
                elif accion == 'Este':
                    dx = 0.3
                elif accion == 'Oeste':
                    dx = -0.3
                plt.arrow(columna, fila, dx, dy, head_width=0.15, head_length=0.15, fc='white', ec='white')  # flechas

    plt.title(titulo)
    plt.xticks([])
    plt.yticks([])
    return plt  # devuelve el objeto plt para guardarlo o mostrarlo más tarde


# inicializacion de la funcion de valor
funcion_valor = np.zeros((LADO_OCEANO, LADO_OCEANO))
funcion_valor[MUELLE] = 0  # el muelle tiene valor 0

# política inicial (aleatoria)
politica_inicial = {}
for fila in range(LADO_OCEANO):
    for columna in range(LADO_OCEANO):
        if (fila, columna) not in ROCAS and (fila, columna) != MUELLE:
            politica_inicial[(fila, columna)] = np.random.choice(ACCIONES)
        else:
            politica_inicial[(fila, columna)] = None  # Roca o Muelle

# dibujar el entorno con la política inicial
plt_inicial = dibujar_entorno(politica_inicial, "Política Inicial")
plt_inicial.show()  # muestra el gráfico inicial

# algoritmo de iteración de valor
iteracion = 0
while True:
    iteracion += 1
    delta = 0  # para verificar la convergencia

    # crear una copia
    funcion_valor_anterior = funcion_valor.copy()

    for fila in range(LADO_OCEANO):
        for columna in range(LADO_OCEANO):
            if es_roca(fila, columna):
                continue  # mo se actualizan las rocas
            if (fila, columna) == MUELLE:
                continue  # so actualiza el valor del muelle

            # calculo del valor de cada celda con la ecuación de Bellman
            valores_acciones = []
            for accion in ACCIONES:
                # calculo del valor esperado de la accion teniendo en cuenta la estocasticidad
                valor_accion = 0
                for nueva_accion in ACCIONES:  # considerar todas las posibles direcciones reales
                    nueva_fila, nueva_columna = transicion(fila, columna, accion)
                    recompensa_inmediata = recompensa(fila, columna, accion)
                    if accion == nueva_accion: # si el viento hace que la dirección se mueva en la dirección que se eligio
                      probabilidad = P_EXITO
                    else: #si el viento afecta a la direccion
                      probabilidad = (1 - P_EXITO)/2  # divide la probabilidad restante entre las otras dos direcciones
                    valor_accion += probabilidad * (recompensa_inmediata + FACTOR_DESCUENTO * funcion_valor[nueva_fila, nueva_columna])

                valores_acciones.append(valor_accion)

            funcion_valor[fila, columna] = max(valores_acciones)
            delta = max(delta, abs(funcion_valor[fila, columna] - funcion_valor_anterior[fila, columna]))
            print("delta: ", delta)

    print(f"Iteración {iteracion}: Delta = {delta}")
    # imprime por consola el valor de cada celda en formato matricial
    for i in range(LADO_OCEANO):
        print(funcion_valor[i, :])
    if delta < TOLERANCIA:
        break

# extraccion de la politica optima
politica_optima = {}
for fila in range(LADO_OCEANO):
    for columna in range(LADO_OCEANO):
        if es_roca(fila, columna):
            politica_optima[(fila, columna)] = "Roca"  # las rocas no tienen politica
            continue
        if (fila, columna) == MUELLE:
            politica_optima[(fila, columna)] = "Muelle"
            continue

        # calculo del valor esperado de cada accion
        valores_acciones = []
        for accion in ACCIONES:
                # clculo del valor esperado de la acción teniendo en cuenta la estocasticidad
                valor_accion = 0
                for nueva_accion in ACCIONES:  # considerar todas las posibles direcciones reales
                    nueva_fila, nueva_columna = transicion(fila, columna, accion)
                    recompensa_inmediata = recompensa(fila, columna, accion)
                    if accion == nueva_accion: # Si el viento hace que la dirección se mueva en la dirección que se eligio
                      probabilidad = P_EXITO
                    else: #si el viento afecta a la dirección
                      probabilidad = (1 - P_EXITO)/2  # divide la probabilidad restante entre las otras dos direcciones
                    valor_accion += probabilidad * (recompensa_inmediata + FACTOR_DESCUENTO * funcion_valor[nueva_fila, nueva_columna])

                valores_acciones.append(valor_accion)

        mejor_accion_indice = np.argmax(valores_acciones)
        politica_optima[(fila, columna)] = ACCIONES[mejor_accion_indice]


# ploteo del entorno con la poiltica optima
plt_optima = dibujar_entorno(politica_optima, "Política Óptima")
plt_optima.show()  # muestra el gráfico final

# impresion por consla de la politica optima
print("\nPolítica Óptima:")
for fila in range(LADO_OCEANO):
    for columna in range(LADO_OCEANO):
        print(f"({fila}, {columna}): {politica_optima[(fila, columna)]}", end="  ")
    print()