# -*- coding: utf-8 -*-
"""dqn_inestable_sin_replay_buffer_sin_target_network_01.ipynb

Automatically generated by Colab.


"""

# ---------------------------------------------------------------------
# ATENCION!
# ESTE ALGORITMO TIENE BAJO RENDIMIENTO, SE COMPARTE A LOS FINES DE
# ANALIZAR Y COMPROBAR QUE DQN SIN REPLAY BUFFER Y SIN TARGET NETWORK NO ES
# UTIL EN NINGUN CASO.
# DEBIDO A ELLO SU EJECUCIÓN PUEDE TARDAR COMO MÍNIMO 1 HORA
# ---------------------------------------------------------------------




# =====================================================================
# Deep Q-Network inestable (sin replay buffer y sin target network)
#
# =====================================================================
# Materia: Aprendizaje por Refuerzo I
# Carrera: Maestria en Inteligencia Artificial - Universidad de Buenos Aires
# Año: 2025
# Docente: Miguel Augusto Azar
# =====================================================================

'''

CartPole-v1 con DQN sin target network ni replay buffer
=======================================================



'''

import gymnasium as gym
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam
import random

#tema oscuro
plt.rcParams.update({
    'figure.facecolor': '#2b2b2b',     # fondo exterior
    'axes.facecolor':   '#2b2b2b',     # fondo del área del gráfico
    'axes.edgecolor':   '#cccccc',     # borde de los ejes
    'axes.labelcolor':  '#cccccc',     # etiquetas de los ejes
    'xtick.color':      '#cccccc',     # color de los números en el eje X
    'ytick.color':      '#cccccc',     # color de los números en el eje Y
    'text.color':       '#cccccc',     # color del título y textos
    'grid.color':       '#444444',     # color de la grilla
})

# --- Hiperparámetros ---
ENV_NAME = "CartPole-v1"
NUM_EPISODES = 500
MAX_STEPS_PER_EPISODE = 500
LEARNING_RATE = 0.001
GAMMA = 0.99  # Factor de descuento
EPSILON_START = 1.0
EPSILON_DECAY = 0.995
EPSILON_MIN = 0.01

# --- Entorno ---
env = gym.make(ENV_NAME)
num_states = env.observation_space.shape[0]
num_actions = env.action_space.n

# --- Red Q (Modelo) ---
def build_model(state_shape, action_shape):
    model = Sequential([
        Dense(24, activation='relu', input_shape=state_shape),
        Dense(24, activation='relu'),
        Dense(action_shape, activation='linear') # Salida lineal para valores Q
    ])
    return model

model = build_model((num_states,), num_actions)
optimizer = Adam(learning_rate=LEARNING_RATE)
loss_function = tf.keras.losses.MeanSquaredError() # Usaremos MSE

# --- Función de selección de acción (Epsilon-Greedy) ---
# El pseudocódigo no lo especifica, pero es necesario para exploración
epsilon = EPSILON_START
def choose_action(state, epsilon):
    if random.random() < epsilon:
        return env.action_space.sample()  # Acción aleatoria (exploración)
    else:
        q_values = model.predict(state[np.newaxis, :], verbose=0) # Añadir dimensión de batch
        return np.argmax(q_values[0]) # Acción greedy (explotación)

# --- Bucle de Entrenamiento ---
episode_rewards = []

for episode in range(NUM_EPISODES):
    state, _ = env.reset()
    total_reward = 0

    for step in range(MAX_STEPS_PER_EPISODE):
        # 1. Elegir acción (necesario para obtener la tupla de experiencia)
        action = choose_action(state, epsilon)

        # 2. Ejecutar acción en el entorno
        next_state, reward, terminated, truncated, _ = env.step(action)
        done = terminated or truncated
        total_reward += reward

        # 3. Calcular el valor Q objetivo (TD Target)
        if done:
            target_q = reward # Objetivo es solo la recompensa si es terminal
        else:
            # Obtener el max Q para el siguiente estado desde la red actual
            next_q_values = model.predict(next_state[np.newaxis, :], verbose=0)
            max_next_q = np.max(next_q_values[0])
            target_q = reward + GAMMA * max_next_q

        # 4. Calcular la pérdida y actualizar la red
        with tf.GradientTape() as tape:
            # Predecir Q(s, :) para el estado actual
            current_q_values = model(state[np.newaxis, :]) # Usar __call__ dentro de GradientTape

            # Queremos que Q(s, action) se acerque a target_q
            # Creamos un "target vector" que es igual a current_q_values
            # excepto en el índice de la acción tomada, donde ponemos target_q
            target_vector = current_q_values.numpy() # Convertir a numpy para modificar
            target_vector[0, action] = target_q

            # Calcular la pérdida entre la predicción y el target_vector
            loss = loss_function(target_vector, current_q_values)

        # 5. Realizar descenso del gradiente
        grads = tape.gradient(loss, model.trainable_variables)
        optimizer.apply_gradients(zip(grads, model.trainable_variables))

        # Actualizar estado
        state = next_state

        if done:
            break

    # Decaimiento de Epsilon
    if epsilon > EPSILON_MIN:
        epsilon *= EPSILON_DECAY
        epsilon = max(EPSILON_MIN, epsilon) # Asegurar que no baje de EPSILON_MIN

    episode_rewards.append(total_reward)
    print(f"Episodio: {episode + 1}/{NUM_EPISODES}, Recompensa: {total_reward}, Epsilon: {epsilon:.4f}")

env.close()

# Puedes graficar episode_rewards para ver el progreso
import matplotlib.pyplot as plt
plt.plot(episode_rewards)
plt.title("Recompensa por Episodio (DQN Base)")
plt.xlabel("Episodio")
plt.ylabel("Recompensa Total")
plt.show()