# -*- coding: utf-8 -*-
"""monte_carlo_on_policy_epsilon_greedy_01.ipynb

Automatically generated by Colab.


"""

# =====================================================================
# Monte Carlo (MC) On-Policy con ε-Greedy
#
# =====================================================================
# _Aprendizaje por Refuerzo I
# _Maestria en Inteligencia Artificial
# _UBA
# _2025
# =====================================================================

'''

Buscador de tesoro en un laberinto
===================================


Dada una cuadricula que representa un laberinto el objetivo es obtener la
politica optima para alcanzar el tesoro partiendo desde A.


+---+---+---+
| A | B | C |  <-- Fila 0
+---+---+---+
| D | E | F |  <-- Fila 1
+---+---+---+
| G | H | I |  <-- Fila 2
+---+---+---+
  ^   ^   ^
Col 0 Col 1 Col 2


Estados: {A, B, C, D, E, F, G, H, I}

Estado Inicial: Siempre empieza en A.

Estados Terminales:

    I (Tesoro): Si llega a I, el episodio termina y recibe una recompensa
                grande (+10).
    F (Trampa): Si llega a F, el episodio termina y recibe una penalización (-5)

Política (π) ε-Greedy

Recompensas (R):

      Entrar en I: +10
      Entrar en F: -5
      Cualquier otro movimiento (o quedarse quieto por chocar): -0.1 (un pequeño
      costo por cada paso/tiempo).

Factor de Descuento: γ = 1.0 (sin descuento, para simplificar). El valor es la
                      suma total de recompensas futuras.


----------------------------------
| A:       | B:       | C:       |
----------------------------------
| D:       | E:       | F (TRAP) |
----------------------------------
| G:       | H:       | I (TRSR) |
----------------------------------


'''
import numpy as np
import random
import collections
from tqdm import tqdm
import matplotlib.pyplot as plt
import matplotlib.patches as patches

# --- Configuración del Entorno 3x3 ---
GRID_ROWS = 3
GRID_COLS = 3
START_STATE = (0, 0)    # Celda 'A'
GOAL_STATE = (2, 2)     # Celda 'I' (Meta)
HOLE_STATE = (1, 2)     # Celda 'F' (Agujero/Penalización)
TERMINAL_STATES = {GOAL_STATE, HOLE_STATE}

# Recompensas
REWARD_GOAL = 10.0
REWARD_HOLE = -5.0
REWARD_STEP = -0.1 # Recompensa por cada paso normal

ACTIONS = {0: 'UP', 1: 'DOWN', 2: 'LEFT', 3: 'RIGHT'}
ACTION_VECTORS = { # Cambios en (dr, dc) para cada acción
    0: (-1, 0), # UP
    1: (1, 0),  # DOWN
    2: (0, -1), # LEFT
    3: (0, 1)   # RIGHT
}
N_ACTIONS = len(ACTIONS)

# --- Parámetros del Algoritmo ---
GAMMA = 1.0          # Factor de descuento
EPSILON = 0.1        # Probabilidad de exploración
NUM_EPISODES = 100000 # Número de episodios para entrenar
MAX_STEPS_PER_EPISODE = GRID_ROWS * GRID_COLS * 3 # Límite de pasos

# --- Funciones Auxiliares ---
def is_valid(state):
    """Comprueba si el estado está dentro de los límites del grid."""
    r, c = state
    return 0 <= r < GRID_ROWS and 0 <= c < GRID_COLS

def take_step(state, action):
    """
    Simula un paso en el entorno determinista.
    Devuelve (next_state, reward, is_terminal).
    """
    if state in TERMINAL_STATES:
        return state, 0, True # Ya está en un terminal

    dr, dc = ACTION_VECTORS[action]
    next_r, next_c = state[0] + dr, state[1] + dc
    next_state = (next_r, next_c)

    # Comprobar límites
    if not is_valid(next_state):
        next_state = state # Chocó con muro, se queda en el mismo lugar
        reward = REWARD_STEP
        is_terminal = False
    # Comprobar estados terminales especiales
    elif next_state == GOAL_STATE:
        reward = REWARD_GOAL
        is_terminal = True
    elif next_state == HOLE_STATE:
        reward = REWARD_HOLE
        is_terminal = True
    # Paso normal a celda no terminal
    else:
        reward = REWARD_STEP
        is_terminal = False

    return next_state, reward, is_terminal

# --- Algoritmo de Control MC On-Policy con ε-Greedy ---

# 1. Inicialización
Q = collections.defaultdict(lambda: np.zeros(N_ACTIONS))
returns_sum = collections.defaultdict(float)
returns_count = collections.defaultdict(float)

print(f"Ejecutando Control MC On-Policy ε-Greedy por {NUM_EPISODES} episodios...")

# 2. Bucle principal de episodios
for episode_num in tqdm(range(NUM_EPISODES)):
    episode_history = []
    state = START_STATE
    terminated = False
    steps = 0
    while not terminated and steps < MAX_STEPS_PER_EPISODE:
        if random.random() < EPSILON:
            action = random.randrange(N_ACTIONS)
        else:
            action = np.argmax(Q[state])
        next_state, reward, terminated = take_step(state, action)
        episode_history.append((state, action, reward))
        state = next_state
        steps += 1
    G = 0
    pairs_visited_in_episode = set()
    for t in range(len(episode_history) - 1, -1, -1):
        state_t, action_t, reward_tp1 = episode_history[t]
        G = GAMMA * G + reward_tp1
        pair = (state_t, action_t)
        if pair not in pairs_visited_in_episode:
            returns_sum[pair] += G
            returns_count[pair] += 1
            if returns_count[pair] > 0: # Evita división por cero
                 Q[state_t][action_t] = returns_sum[pair] / returns_count[pair]
            # La política se actualiza implícitamente al usar Q en el siguiente episodio
            pairs_visited_in_episode.add(pair)

# --- Muestra de Resultados (COLORES ACTUALIZADOS) ---
print("\n--- Entrenamiento Completado ---")
print("\nPolítica Óptima Derivada (π*) - Greedy respecto a Q aprendido:")

# Derivar la política greedy final a partir de Q
final_policy = {}
all_states = [(r, c) for r in range(GRID_ROWS) for c in range(GRID_COLS)]
for s in all_states:
    if s not in TERMINAL_STATES:
        # Si un estado nunca fue visitado, Q[s] será [0,0,0,0], argmax dará 0 (UP)
        # Podríamos asignar una acción aleatoria o un símbolo especial si se prefiere
        final_policy[s] = np.argmax(Q[s])

# Visualización con Matplotlib (COLORES ACTUALIZADOS)
action_symbols = {0: '^', 1: 'v', 2: '<', 3: '>'}
fig, ax = plt.subplots(figsize=(5.5, 5.5)) # Ajusta tamaño si es necesario

# --- Definición de Colores Solicitados ---
#color_fondo_normal = 'dimgray'      # Fondo de celda normal: Gris Oscuro
color_fondo_normal = '0.2'      # Fondo de celda normal: Gris Oscuro

color_agujero = 'red'           # Celda F: Roja
color_meta = 'darkgreen'        # Celda I: Verde Oscuro
color_borde_celda = 'black'     # Borde de celdas: Negro (mantenido)
color_lineas_grid = 'royalblue'      # Líneas de la grilla: Azul
color_flecha = 'orange'         # Flechas de política: Naranja
color_fondo_figura_ejes = '0.2' # Fondo alrededor de la grilla y detrás: Gris muy oscuro (20%)
color_titulo = 'white'          # Color del título: Blanco

# --- Función para graficar la cuadrícula base (Adaptada) ---
def plot_grid_base_updated(ax):
    for r in range(GRID_ROWS):
        for c in range(GRID_COLS):
            state = (r, c)
            color = color_fondo_normal # Color por defecto GRIS OSCURO
            text = ""
            text_color = 'lightgrey' # Color por defecto para texto (si se añade)

            if state == GOAL_STATE:
                color = color_meta
                text = "I" # <- Meta
                text_color = 'white'
            elif state == HOLE_STATE:
                color = color_agujero
                text = "F" # <- Agujero
                text_color = 'white'

            rect = patches.Rectangle((c, r), 1, 1, linewidth=1, edgecolor=color_borde_celda, facecolor=color, alpha=0.9) # Ajusta alpha si es necesario
            ax.add_patch(rect)
            if text:
                 ax.text(c + 0.5, r + 0.5, text, ha='center', va='center', color=text_color, weight='bold', fontsize=12)

    # Configura los ejes
    ax.set_xticks(np.arange(GRID_COLS + 1), minor=False)
    ax.set_yticks(np.arange(GRID_ROWS + 1), minor=False)
    ax.set_xticklabels([])
    ax.set_yticklabels([])
    # Usa el color azul para la grilla
    ax.grid(True, which='major', color=color_lineas_grid, linewidth=1.5, linestyle='-')
    ax.set_xlim(0, GRID_COLS)
    ax.set_ylim(GRID_ROWS, 0) # Origen (0,0) arriba a la izquierda
    ax.set_aspect('equal', adjustable='box')
    # Elimina los bordes/spines del eje para que solo se vea la grilla azul
    for spine in ax.spines.values():
        spine.set_visible(False)

# Aplicar colores de fondo a figura y ejes
fig.set_facecolor(color_fondo_figura_ejes)
ax.set_facecolor(color_fondo_figura_ejes)

# Dibuja la base actualizada
plot_grid_base_updated(ax)

# Dibuja flechas de la política (NARANJA)
arrow_params = dict(width=0.08, head_width=0.25, head_length=0.18, fc=color_flecha, ec=color_flecha) # fc=facecolor, ec=edgecolor
for r in range(GRID_ROWS):
    for c in range(GRID_COLS):
        state = (r, c)
        if state not in TERMINAL_STATES:
            action_idx = final_policy.get(state, -1) # Usa -1 si el estado no está en la política
            if action_idx != -1:
                dr, dc = ACTION_VECTORS[action_idx]
                arrow_len_factor = 0.3
                ax.arrow(c + 0.5 - dc*(arrow_len_factor/2),
                         r + 0.5 - dr*(arrow_len_factor/2),
                         dc * arrow_len_factor, # dx
                         dr * arrow_len_factor, # dy
                         **arrow_params)

# Configura título
ax.set_title(f'Política MC On-Policy ε-Greedy (ε={EPSILON})', color=color_titulo)

plt.tight_layout() # Ajusta para evitar solapamientos
plt.show()